# This is a basic workflow to help you get started with Actions

name: POC

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: poiky/cura
    
    # Steps
    # Checkout repo
    # Determine wich stl to slice (possibly base this from a diff with previous commit?)
    # use curaengine.exe with config in repo to generate the slicing command (config includes: filament, extruder temp, build plate temp, layer height, infill,
      # infill pattern, printer, support, support angle, support placement, build plate adhesion, 
    # output gcode at the same path as the stl
    # commit and push to master
      
    # Checkout new master
    # upload file to 3d printer
      # defined in config file
    # Begin 3d printing
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: /CuraEngine/build/CuraEngine help

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
